---
title: "20191025_PCA_in_R"
author: "Patrick Bruck"
date: "10/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Reading in our example data:
```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV", row.names = 1)
  #row.names = 1 tells it that the first column is just names for the rows, not data
mydata
```


We call prcomp() to do PCA.
This function expects the rows to be samples, and columns to be genes, so we have to transpose the matrix with t().
```{r}
pca <- prcomp(t(mydata), scale = TRUE)
attributes(pca)
```


```{r}
summary(pca)
  #summary(pca) gives stats on diff PC's, including proportion of variation explained by each PC.

plot(pca$x[,1])
plot(pca$x[,1], pca$x[,2])
  ## Gives basic graph of PC1 vs PC2. Precent variance is often more informative to look at
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var.per

pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main="Scree Plot",
        xlab="Principal Component", ylab="Percent Variation")
  #give Scree plot
   
```


Add group colors to plot:
```{r}
colnames(mydata)
 ## A vector of colors for wt and ko samples
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
     xlab=paste0("PC1 (", pca.var.per[1], "%)"),
     ylab=paste0("PC2 (", pca.var.per[2], "%)"))
```












New excercise: PCA on UK food data
https://bioboot.github.io/bggn213_W19/class-material/lab-8-bggn213.html

```{r}
x <- read.csv("UK_foods.csv", row.names = 1)
x
dim(x); nrow(x); ncol(x)
head(x)
```


Spotting major differences and trends
```{r}
barplot(as.matrix(x), beside=T, col=rainbow(nrow(x)))
barplot(as.matrix(x), beside=FALSE, col=rainbow(nrow(x)))
pairs(x, col=rainbow(10), pch=16)
```






```{r}
pca <- prcomp(t(x))
summary(pca)
plot(pca)

plot(pca$x[,1:2], xlab="PC1", ylab="PC2", xlim=c(-270,500), col = colorvector)
colorvector <- c("yellow2", "pink", "blue", "green4")
text(pca$x[,1:2], colnames(x), col = colorvector)
```





```{r}
v <- round( pca$sdev^2/sum(pca$sdev^2) * 100 )
barplot(v, xlab="Principal Component", ylab="Percent Variation")
z <- summary(pca)
z$importance
barplot(v, xlab="Principal Component", ylab="Percent Variation")

#digging into PC1 to see what explains differences in Northern Ireland
par(mar=c(10, 3, 0.35, 0))
barplot( pca$rotation[,1], las=2 )
biplot(pca)
```

