---
title: "Class 6 R Functions"
author: "Patrick Bruck"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is a level 1 heading
Some smaller text goes here, not a header

## Two hashes makes a level 2

### And 3 is a level 3. This is the smallest text







```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```


```{r}
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
points(s2.b, type="l", col="blue", lwd=2)
```


```{r}
s1 <- read.pdb("4AKE")  # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
```





HOMEWORK Q6:

Try to make a function to get streamline this analysis:
```{r}

# Creating condense(), a program to read, trim, and plot the B-factor for each residue of a
# protein of interest.

condense <- function(x){
  A <- read.pdb(x)
  B <- trim.pdb(A, chain = "A", elety = "CA")
  C <- B$atom$b
  plotb3(C, sse = B, typ = "l", ylab = "Bfactor")
  
}

# Outputs a plot showing the B-factor for each residue of the protein.

# Run as condense("protein-of-interest-from-pdb")
condense("4AKE")
```

